// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: indicator_ha

#ifndef UI_SCREEN_DISPLAY_H
#define UI_SCREEN_DISPLAY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_display
extern void ui_screen_display_screen_init(void);
extern void ui_screen_display_screen_destroy(void);
extern lv_obj_t * ui_screen_display;
extern lv_obj_t * ui_sleep_mode_time;
extern lv_obj_t * ui_after1;
extern void ui_event_sleep_mode_time_cfg(lv_event_t * e);
extern lv_obj_t * ui_sleep_mode_time_cfg;
extern lv_obj_t * ui_min1;
extern lv_obj_t * ui_sleep_mode;
extern lv_obj_t * ui_sleep_mode_title;
extern void ui_event_sleep_mode_cfg(lv_event_t * e);
extern lv_obj_t * ui_sleep_mode_cfg;
extern lv_obj_t * ui_brighness1;
extern void ui_event_brighness_cfg(lv_event_t * e);
extern lv_obj_t * ui_brighness_cfg;
extern lv_obj_t * ui_brighness_title;
extern lv_obj_t * ui_brighness_icon_3;
extern lv_obj_t * ui_brighness_icon_4;
extern void ui_event_display_keyboard(lv_event_t * e);
extern lv_obj_t * ui_display_keyboard;
extern lv_obj_t * ui_display_title1;
extern void ui_event_back3(lv_event_t * e);
extern lv_obj_t * ui_back3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

