// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: indicator_ha

#ifndef UI_SCREEN_SETTING_H
#define UI_SCREEN_SETTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_setting
extern void ui_screen_setting_screen_init(void);
extern void ui_screen_setting_screen_destroy(void);
extern void ui_event_screen_setting(lv_event_t * e);
extern lv_obj_t * ui_screen_setting;
extern lv_obj_t * ui_panel_top_4;
extern lv_obj_t * ui_time_ha_data3;
extern void ui_event_wifi__st_button_ha_setting(lv_event_t * e);
extern lv_obj_t * ui_wifi__st_button_ha_setting;
extern lv_obj_t * ui_wifi_st_4;
extern lv_obj_t * ui_Container_Setting;
extern lv_obj_t * ui_setting_title1;
extern lv_obj_t * ui_setting_icon1;
extern void ui_event_setting_wifi1(lv_event_t * e);
extern lv_obj_t * ui_setting_wifi1;
extern lv_obj_t * ui_setting_wifi_icon1;
extern lv_obj_t * ui_setting_wifi_title1;
extern void ui_event_setting_display1(lv_event_t * e);
extern lv_obj_t * ui_setting_display1;
extern lv_obj_t * ui_setting_display_icon1;
extern lv_obj_t * ui_setting_display_title1;
extern lv_obj_t * ui_scrolldots1;
extern lv_obj_t * ui_scrolldots2;
extern lv_obj_t * ui_scrolldots4;
extern lv_obj_t * ui_scrolldots5;
extern void ui_event_setting_display2(lv_event_t * e);
extern lv_obj_t * ui_setting_display2;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

