// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: indicator_ha

#include "../ui.h"

lv_obj_t * ui_screen_wifi = NULL;
lv_obj_t * ui_panel_top_5 = NULL;
lv_obj_t * ui_back_wifi = NULL;
lv_obj_t * ui_screen_home_data_label4 = NULL;
lv_obj_t * ui_wifi__st_button_ha_data4 = NULL;
lv_obj_t * ui_wifi_st_0 = NULL;
lv_obj_t * ui_wifi_scan_wait = NULL;
lv_obj_t * ui_temp_image1 = NULL;
// event funtions
void ui_event_screen_wifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ui_event_wifi_config(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        ui_event_wifi_start(e);
    }
}

void ui_event_back_wifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screen_setting, LV_SCR_LOAD_ANIM_OVER_TOP, 200, 0, &ui_screen_setting_screen_init);
    }
}

// build funtions

void ui_screen_wifi_screen_init(void)
{
    ui_screen_wifi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screen_wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_panel_top_5 = lv_obj_create(ui_screen_wifi);
    lv_obj_set_width(ui_panel_top_5, 480);
    lv_obj_set_height(ui_panel_top_5, 85);
    lv_obj_set_align(ui_panel_top_5, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_panel_top_5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel_top_5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_top_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_top_5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_top_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_back_wifi = lv_btn_create(ui_panel_top_5);
    lv_obj_set_width(ui_back_wifi, 100);
    lv_obj_set_height(ui_back_wifi, 50);
    lv_obj_set_x(ui_back_wifi, -15);
    lv_obj_set_y(ui_back_wifi, 0);
    lv_obj_add_flag(ui_back_wifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_back_wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_back_wifi, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_back_wifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_back_wifi, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screen_home_data_label4 = lv_label_create(ui_panel_top_5);
    lv_obj_set_width(ui_screen_home_data_label4, 316);
    lv_obj_set_height(ui_screen_home_data_label4, 21);
    lv_obj_set_align(ui_screen_home_data_label4, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_screen_home_data_label4, "Wi-Fi");
    lv_obj_set_style_text_color(ui_screen_home_data_label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_screen_home_data_label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_screen_home_data_label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_screen_home_data_label4, &ui_font_font0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi__st_button_ha_data4 = lv_btn_create(ui_panel_top_5);
    lv_obj_set_width(ui_wifi__st_button_ha_data4, 60);
    lv_obj_set_height(ui_wifi__st_button_ha_data4, 60);
    lv_obj_set_align(ui_wifi__st_button_ha_data4, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_wifi__st_button_ha_data4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifi__st_button_ha_data4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifi__st_button_ha_data4, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifi__st_button_ha_data4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_wifi__st_button_ha_data4, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi_st_0 = lv_img_create(ui_wifi__st_button_ha_data4);
    lv_img_set_src(ui_wifi_st_0, &ui_img_wifi_disconet_png);
    lv_obj_set_width(ui_wifi_st_0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi_st_0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifi_st_0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi_st_0, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifi_st_0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifi_scan_wait = lv_spinner_create(ui_screen_wifi, 1000, 90);
    lv_obj_set_width(ui_wifi_scan_wait, 50);
    lv_obj_set_height(ui_wifi_scan_wait, 50);
    lv_obj_set_align(ui_wifi_scan_wait, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wifi_scan_wait, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_temp_image1 = lv_img_create(ui_screen_wifi);
    lv_img_set_src(ui_temp_image1, &ui_img_lock_png);
    lv_obj_set_width(ui_temp_image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp_image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp_image1, 193);
    lv_obj_set_y(ui_temp_image1, 197);
    lv_obj_set_align(ui_temp_image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_temp_image1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_temp_image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_back_wifi, ui_event_back_wifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screen_wifi, ui_event_screen_wifi, LV_EVENT_ALL, NULL);

}

void ui_screen_wifi_screen_destroy(void)
{
    if(ui_screen_wifi) lv_obj_del(ui_screen_wifi);

    // NULL screen variables
    ui_screen_wifi = NULL;
    ui_panel_top_5 = NULL;
    ui_back_wifi = NULL;
    ui_screen_home_data_label4 = NULL;
    ui_wifi__st_button_ha_data4 = NULL;
    ui_wifi_st_0 = NULL;
    ui_wifi_scan_wait = NULL;
    ui_temp_image1 = NULL;

}
