// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: indicator_ha

#ifndef UI_SCREEN_BROKER_H
#define UI_SCREEN_BROKER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_broker
extern void ui_screen_broker_screen_init(void);
extern void ui_screen_broker_screen_destroy(void);
extern lv_obj_t * ui_screen_broker;
extern lv_obj_t * ui_panel_top_6;
extern void ui_event_back_wifi1(lv_event_t * e);
extern lv_obj_t * ui_back_wifi1;
extern lv_obj_t * ui_screen_home_data_label5;
extern void ui_event_wifi__st_button_ha_data3(lv_event_t * e);
extern lv_obj_t * ui_wifi__st_button_ha_data3;
extern lv_obj_t * ui_wifi_st_01;
extern lv_obj_t * ui_container_Inputer;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern void ui_event_textarea_ip_0(lv_event_t * e);
extern lv_obj_t * ui_textarea_ip_0;
extern lv_obj_t * ui_Label4;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Container2;
extern void ui_event_Keyboard_ip(lv_event_t * e);
extern lv_obj_t * ui_Keyboard_ip;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

