// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: indicator_ha

#include "../ui.h"

lv_obj_t * ui_screen_ha_mix = NULL;
lv_obj_t * ui_sensor5_btn1 = NULL;
lv_obj_t * ui_sensor5_logo1 = NULL;
lv_obj_t * ui_sensor5_label1 = NULL;
lv_obj_t * ui_sensor_data_temp_1 = NULL;
lv_obj_t * ui_sensor5_unit1 = NULL;
lv_obj_t * ui_sensor6_btn1 = NULL;
lv_obj_t * ui_sensor6_logo1 = NULL;
lv_obj_t * ui_sensor6_label1 = NULL;
lv_obj_t * ui_sensor_data_humi_1 = NULL;
lv_obj_t * ui_sensor6_unit1 = NULL;
lv_obj_t * ui_switch1 = NULL;
lv_obj_t * ui_switch1_logo1 = NULL;
lv_obj_t * ui_switch1_label1 = NULL;
lv_obj_t * ui_panel_top_2 = NULL;
lv_obj_t * ui_time_ha_data1 = NULL;
lv_obj_t * ui_screen_home_data_label2 = NULL;
lv_obj_t * ui_wifi__st_button_ha_data1 = NULL;
lv_obj_t * ui_wifi_st_1 = NULL;
lv_obj_t * ui_switch2 = NULL;
lv_obj_t * ui_switch1_logo2 = NULL;
lv_obj_t * ui_switch1_label2 = NULL;
lv_obj_t * ui_switch3 = NULL;
lv_obj_t * ui_switch1_logo3 = NULL;
lv_obj_t * ui_switch1_label3 = NULL;
// event funtions
void ui_event_screen_ha_mix(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_screen_setting, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_screen_setting_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_screen_setting, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_screen_setting_screen_init);
    }
}

void ui_event_switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_image_set_property(ui_switch1_logo1, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_alarm_on_2_png);
        switch_event_cb(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_image_set_property(ui_switch1_logo1, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_alarm_off_png);
        switch_event_cb(e);
    }
}

void ui_event_wifi__st_button_ha_data1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screen_wifi, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 200, 0, &ui_screen_wifi_screen_init);
    }
}

void ui_event_switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_image_set_property(ui_switch1_logo2, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_door_open_2_png);
        switch_event_cb(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_image_set_property(ui_switch1_logo2, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_door_closed_png);
        switch_event_cb(e);
    }
}

void ui_event_switch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_image_set_property(ui_switch1_logo3, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_ic_switch2_on_png);
        switch_event_cb(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_image_set_property(ui_switch1_logo3, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_ic_switch2_off_png);
        switch_event_cb(e);
    }
}

// build funtions

void ui_screen_ha_mix_screen_init(void)
{
    ui_screen_ha_mix = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screen_ha_mix, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sensor5_btn1 = lv_btn_create(ui_screen_ha_mix);
    lv_obj_set_width(ui_sensor5_btn1, 214);
    lv_obj_set_height(ui_sensor5_btn1, 164);
    lv_obj_set_x(ui_sensor5_btn1, 22);
    lv_obj_set_y(ui_sensor5_btn1, 96);
    lv_obj_add_flag(ui_sensor5_btn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sensor5_btn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_sensor5_btn1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sensor5_btn1, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sensor5_btn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensor5_logo1 = lv_img_create(ui_sensor5_btn1);
    lv_img_set_src(ui_sensor5_logo1, &ui_img_ic_temp_png);
    lv_obj_set_width(ui_sensor5_logo1, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_sensor5_logo1, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_sensor5_logo1, 69);
    lv_obj_set_y(ui_sensor5_logo1, 22);
    lv_obj_add_flag(ui_sensor5_logo1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sensor5_logo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sensor5_label1 = lv_label_create(ui_sensor5_btn1);
    lv_obj_set_width(ui_sensor5_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sensor5_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sensor5_label1, 0);
    lv_obj_set_y(ui_sensor5_label1, -5);
    lv_obj_set_align(ui_sensor5_label1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_sensor5_label1, "Temp");
    lv_obj_set_style_text_color(ui_sensor5_label1, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sensor5_label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sensor5_label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensor_data_temp_1 = lv_label_create(ui_sensor5_btn1);
    lv_obj_set_width(ui_sensor_data_temp_1, 100);
    lv_obj_set_height(ui_sensor_data_temp_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sensor_data_temp_1, 14);
    lv_obj_set_y(ui_sensor_data_temp_1, 83);
    lv_label_set_text(ui_sensor_data_temp_1, "N/A");
    lv_obj_set_style_text_color(ui_sensor_data_temp_1, lv_color_hex(0xECBF41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sensor_data_temp_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_sensor_data_temp_1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sensor_data_temp_1, &ui_font_font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensor5_unit1 = lv_label_create(ui_sensor5_btn1);
    lv_obj_set_width(ui_sensor5_unit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sensor5_unit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sensor5_unit1, 125);
    lv_obj_set_y(ui_sensor5_unit1, 85);
    lv_label_set_text(ui_sensor5_unit1, "°C");
    lv_obj_set_style_text_color(ui_sensor5_unit1, lv_color_hex(0xECBF41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sensor5_unit1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sensor5_unit1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensor6_btn1 = lv_btn_create(ui_screen_ha_mix);
    lv_obj_set_width(ui_sensor6_btn1, 214);
    lv_obj_set_height(ui_sensor6_btn1, 164);
    lv_obj_set_x(ui_sensor6_btn1, 244);
    lv_obj_set_y(ui_sensor6_btn1, 96);
    lv_obj_add_flag(ui_sensor6_btn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sensor6_btn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_sensor6_btn1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sensor6_btn1, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sensor6_btn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensor6_logo1 = lv_img_create(ui_sensor6_btn1);
    lv_img_set_src(ui_sensor6_logo1, &ui_img_ic_hum_png);
    lv_obj_set_width(ui_sensor6_logo1, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_sensor6_logo1, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_sensor6_logo1, 69);
    lv_obj_set_y(ui_sensor6_logo1, 22);
    lv_obj_add_flag(ui_sensor6_logo1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sensor6_logo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sensor6_label1 = lv_label_create(ui_sensor6_btn1);
    lv_obj_set_width(ui_sensor6_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sensor6_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sensor6_label1, 0);
    lv_obj_set_y(ui_sensor6_label1, -5);
    lv_obj_set_align(ui_sensor6_label1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_sensor6_label1, "Humidity");
    lv_obj_set_style_text_color(ui_sensor6_label1, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sensor6_label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sensor6_label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensor_data_humi_1 = lv_label_create(ui_sensor6_btn1);
    lv_obj_set_width(ui_sensor_data_humi_1, 100);
    lv_obj_set_height(ui_sensor_data_humi_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sensor_data_humi_1, 13);
    lv_obj_set_y(ui_sensor_data_humi_1, 83);
    lv_label_set_text(ui_sensor_data_humi_1, "N/A");
    lv_obj_set_style_text_color(ui_sensor_data_humi_1, lv_color_hex(0x52AAE5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sensor_data_humi_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_sensor_data_humi_1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sensor_data_humi_1, &ui_font_font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensor6_unit1 = lv_label_create(ui_sensor6_btn1);
    lv_obj_set_width(ui_sensor6_unit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sensor6_unit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sensor6_unit1, 125);
    lv_obj_set_y(ui_sensor6_unit1, 83);
    lv_label_set_text(ui_sensor6_unit1, "%");
    lv_obj_set_style_text_color(ui_sensor6_unit1, lv_color_hex(0x52AAE5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sensor6_unit1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sensor6_unit1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch1 = lv_btn_create(ui_screen_ha_mix);
    lv_obj_set_width(ui_switch1, 214);
    lv_obj_set_height(ui_switch1, 164);
    lv_obj_set_x(ui_switch1, 22);
    lv_obj_set_y(ui_switch1, 268);
    lv_obj_add_flag(ui_switch1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_switch1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_switch1, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_switch1, 20, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_switch1, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_switch1, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_switch1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_switch1, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_switch1_logo1 = lv_img_create(ui_switch1);
    lv_img_set_src(ui_switch1_logo1, &ui_img_alarm_off_png);
    lv_obj_set_width(ui_switch1_logo1, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_switch1_logo1, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_switch1_logo1, 39);
    lv_obj_set_y(ui_switch1_logo1, 10);
    lv_obj_add_flag(ui_switch1_logo1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_switch1_logo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_switch1_logo1, &ui_img_alarm_on_2_png, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_switch1_label1 = lv_label_create(ui_switch1);
    lv_obj_set_width(ui_switch1_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_switch1_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_switch1_label1, 0);
    lv_obj_set_y(ui_switch1_label1, -5);
    lv_obj_set_align(ui_switch1_label1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_switch1_label1, "Alarm an / aus");
    lv_obj_set_style_text_color(ui_switch1_label1, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_switch1_label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_switch1_label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel_top_2 = lv_obj_create(ui_screen_ha_mix);
    lv_obj_set_width(ui_panel_top_2, 480);
    lv_obj_set_height(ui_panel_top_2, 100);
    lv_obj_set_align(ui_panel_top_2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_panel_top_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel_top_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_top_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_top_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_top_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time_ha_data1 = lv_label_create(ui_panel_top_2);
    lv_obj_set_width(ui_time_ha_data1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time_ha_data1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time_ha_data1, 15);
    lv_obj_set_y(ui_time_ha_data1, 0);
    lv_obj_set_align(ui_time_ha_data1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_time_ha_data1, "21:20");
    lv_obj_add_flag(ui_time_ha_data1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_time_ha_data1, &ui_font_font0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screen_home_data_label2 = lv_label_create(ui_panel_top_2);
    lv_obj_set_width(ui_screen_home_data_label2, 316);
    lv_obj_set_height(ui_screen_home_data_label2, 21);
    lv_obj_set_align(ui_screen_home_data_label2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_screen_home_data_label2, "Home Assistant\n");
    lv_obj_set_style_text_color(ui_screen_home_data_label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_screen_home_data_label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_screen_home_data_label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_screen_home_data_label2, &ui_font_font0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi__st_button_ha_data1 = lv_btn_create(ui_panel_top_2);
    lv_obj_set_width(ui_wifi__st_button_ha_data1, 60);
    lv_obj_set_height(ui_wifi__st_button_ha_data1, 60);
    lv_obj_set_align(ui_wifi__st_button_ha_data1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_wifi__st_button_ha_data1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifi__st_button_ha_data1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifi__st_button_ha_data1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifi__st_button_ha_data1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_wifi__st_button_ha_data1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi_st_1 = lv_img_create(ui_wifi__st_button_ha_data1);
    lv_img_set_src(ui_wifi_st_1, &ui_img_wifi_disconet_png);
    lv_obj_set_width(ui_wifi_st_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi_st_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifi_st_1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi_st_1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifi_st_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_switch2 = lv_btn_create(ui_screen_ha_mix);
    lv_obj_set_width(ui_switch2, 214);
    lv_obj_set_height(ui_switch2, 164);
    lv_obj_set_x(ui_switch2, 244);
    lv_obj_set_y(ui_switch2, 268);
    lv_obj_add_flag(ui_switch2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_switch2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_switch2, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_switch2, 20, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_switch2, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_switch2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_switch2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_switch2, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_switch1_logo2 = lv_img_create(ui_switch2);
    lv_img_set_src(ui_switch1_logo2, &ui_img_door_closed_png);
    lv_obj_set_width(ui_switch1_logo2, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_switch1_logo2, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_switch1_logo2, 39);
    lv_obj_set_y(ui_switch1_logo2, 10);
    lv_obj_add_flag(ui_switch1_logo2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_switch1_logo2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_switch1_logo2, &ui_img_door_closed_png, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_switch1_label2 = lv_label_create(ui_switch2);
    lv_obj_set_width(ui_switch1_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_switch1_label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_switch1_label2, 0);
    lv_obj_set_y(ui_switch1_label2, -5);
    lv_obj_set_align(ui_switch1_label2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_switch1_label2, "Offene Fenster");
    lv_obj_set_style_text_color(ui_switch1_label2, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_switch1_label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_switch1_label2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch3 = lv_btn_create(ui_screen_ha_mix);
    lv_obj_set_width(ui_switch3, 432);
    lv_obj_set_height(ui_switch3, 164);
    lv_obj_set_x(ui_switch3, 22);
    lv_obj_set_y(ui_switch3, 268);
    lv_obj_add_flag(ui_switch3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_switch3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_switch3, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_switch3, 20, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_switch3, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_switch3, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_switch3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_switch3, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_switch1_logo3 = lv_img_create(ui_switch3);
    lv_img_set_src(ui_switch1_logo3, &ui_img_ic_switch2_off_png);
    lv_obj_set_width(ui_switch1_logo3, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_switch1_logo3, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_switch1_logo3, 0);
    lv_obj_set_y(ui_switch1_logo3, 10);
    lv_obj_set_align(ui_switch1_logo3, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_switch1_logo3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_switch1_logo3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_switch1_label3 = lv_label_create(ui_switch3);
    lv_obj_set_width(ui_switch1_label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_switch1_label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_switch1_label3, 0);
    lv_obj_set_y(ui_switch1_label3, -5);
    lv_obj_set_align(ui_switch1_label3, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_switch1_label3, "Alarm RESET");
    lv_obj_set_style_text_color(ui_switch1_label3, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_switch1_label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_switch1_label3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_switch1, ui_event_switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifi__st_button_ha_data1, ui_event_wifi__st_button_ha_data1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switch2, ui_event_switch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switch3, ui_event_switch3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screen_ha_mix, ui_event_screen_ha_mix, LV_EVENT_ALL, NULL);

}

void ui_screen_ha_mix_screen_destroy(void)
{
    if(ui_screen_ha_mix) lv_obj_del(ui_screen_ha_mix);

    // NULL screen variables
    ui_screen_ha_mix = NULL;
    ui_sensor5_btn1 = NULL;
    ui_sensor5_logo1 = NULL;
    ui_sensor5_label1 = NULL;
    ui_sensor_data_temp_1 = NULL;
    ui_sensor5_unit1 = NULL;
    ui_sensor6_btn1 = NULL;
    ui_sensor6_logo1 = NULL;
    ui_sensor6_label1 = NULL;
    ui_sensor_data_humi_1 = NULL;
    ui_sensor6_unit1 = NULL;
    ui_switch1 = NULL;
    ui_switch1_logo1 = NULL;
    ui_switch1_label1 = NULL;
    ui_panel_top_2 = NULL;
    ui_time_ha_data1 = NULL;
    ui_screen_home_data_label2 = NULL;
    ui_wifi__st_button_ha_data1 = NULL;
    ui_wifi_st_1 = NULL;
    ui_switch2 = NULL;
    ui_switch1_logo2 = NULL;
    ui_switch1_label2 = NULL;
    ui_switch3 = NULL;
    ui_switch1_logo3 = NULL;
    ui_switch1_label3 = NULL;

}
