// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: indicator_ha

#ifndef UI_SCREEN_HA_MIX_H
#define UI_SCREEN_HA_MIX_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_ha_mix
extern void ui_screen_ha_mix_screen_init(void);
extern void ui_screen_ha_mix_screen_destroy(void);
extern void ui_event_screen_ha_mix(lv_event_t * e);
extern lv_obj_t * ui_screen_ha_mix;
extern lv_obj_t * ui_sensor5_btn1;
extern lv_obj_t * ui_sensor5_logo1;
extern lv_obj_t * ui_sensor5_label1;
extern lv_obj_t * ui_sensor_data_temp_1;
extern lv_obj_t * ui_sensor5_unit1;
extern lv_obj_t * ui_sensor6_btn1;
extern lv_obj_t * ui_sensor6_logo1;
extern lv_obj_t * ui_sensor6_label1;
extern lv_obj_t * ui_sensor_data_humi_1;
extern lv_obj_t * ui_sensor6_unit1;
extern void ui_event_switch1(lv_event_t * e);
extern lv_obj_t * ui_switch1;
extern lv_obj_t * ui_switch1_logo1;
extern lv_obj_t * ui_switch1_label1;
extern lv_obj_t * ui_panel_top_2;
extern lv_obj_t * ui_time_ha_data1;
extern lv_obj_t * ui_screen_home_data_label2;
extern void ui_event_wifi__st_button_ha_data1(lv_event_t * e);
extern lv_obj_t * ui_wifi__st_button_ha_data1;
extern lv_obj_t * ui_wifi_st_1;
extern void ui_event_switch2(lv_event_t * e);
extern lv_obj_t * ui_switch2;
extern lv_obj_t * ui_switch1_logo2;
extern lv_obj_t * ui_switch1_label2;
extern void ui_event_switch3(lv_event_t * e);
extern lv_obj_t * ui_switch3;
extern lv_obj_t * ui_switch1_logo3;
extern lv_obj_t * ui_switch1_label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

