// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: indicator_ha

#ifndef UI_SCREEN_WIFI_H
#define UI_SCREEN_WIFI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_wifi
extern void ui_screen_wifi_screen_init(void);
extern void ui_screen_wifi_screen_destroy(void);
extern void ui_event_screen_wifi(lv_event_t * e);
extern lv_obj_t * ui_screen_wifi;
extern lv_obj_t * ui_panel_top_5;
extern void ui_event_back_wifi(lv_event_t * e);
extern lv_obj_t * ui_back_wifi;
extern lv_obj_t * ui_screen_home_data_label4;
extern lv_obj_t * ui_wifi__st_button_ha_data4;
extern lv_obj_t * ui_wifi_st_0;
extern lv_obj_t * ui_wifi_scan_wait;
extern lv_obj_t * ui_temp_image1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

