// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: indicator_ha

#ifndef _INDICATOR_HA_UI_H
#define _INDICATOR_HA_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_screen_ha_mix.h"
#include "screens/ui_screen_setting.h"
#include "screens/ui_screen_wifi.h"
#include "screens/ui_screen_display.h"
#include "screens/ui_screen_broker.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_ic_temp_png);    // assets/ic_temp.png
LV_IMG_DECLARE(ui_img_ic_hum_png);    // assets/ic_hum.png
LV_IMG_DECLARE(ui_img_ic_switch2_on_png);    // assets/ic_switch2_on.png
LV_IMG_DECLARE(ui_img_ic_switch2_off_png);    // assets/ic_switch2_off.png
LV_IMG_DECLARE(ui_img_wifi_disconet_png);    // assets/wifi_disconet.png
LV_IMG_DECLARE(ui_img_setting_png);    // assets/setting.png
LV_IMG_DECLARE(ui_img_wifi_setting_png);    // assets/wifi_setting.png
LV_IMG_DECLARE(ui_img_display_png);    // assets/display.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_lock_png);    // assets/lock.png
LV_IMG_DECLARE(ui_img_high_light_png);    // assets/high_light.png
LV_IMG_DECLARE(ui_img_low_light_png);    // assets/low_light.png

// FONTS
LV_FONT_DECLARE(ui_font_font0);
LV_FONT_DECLARE(ui_font_font2);
LV_FONT_DECLARE(ui_font_font3);
LV_FONT_DECLARE(ui_font_font4);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
